# 数据源配置
spring:
    redis:
        host: 127.0.0.1
        port: 6379
        # 连接超时时间（记得添加单位，Duration）
        timeout: 10000ms
        # Redis默认情况下有16个分片，这里配置具体使用的分片
        # database: 0
        lettuce:
            pool:
                # 连接池最大连接数（使用负值表示没有限制） 默认 8
                max-active: 8
                # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
                max-wait: -1ms
                # 连接池中的最大空闲连接 默认 8
                max-idle: 8
                # 连接池中的最小空闲连接 默认 0
                min-idle: 0
        cache:
            # 一般来说是不用配置的，Spring Cache 会根据依赖的包自行装配
            type: redis
    data:
        mongodb:
            host: 127.0.0.1
            port: 27017
            database: oms
    rabbitmq:
        host: 127.0.0.1
        post: 5672
        username: guest
        password: guest
        listener:
            concurrency: 10
            max-concurrency: 20
            prefetch: 5
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        druid:
            # 主库数据源
            master:
                url: jdbc:mysql://115.159.201.193:3306/oms-fast?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
                username: oms-fast
                password: 123456
            # 从库数据源
            slave:
                # 从数据源开关/默认关闭
                enabled: false
                url: jdbc:mysql://127.0.0.1:3306/rds?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
                username: root
                password: 123456
            # 初始连接数
            initialSize: 5
            # 最小连接池数量
            minIdle: 10
            # 最大连接池数量
            maxActive: 20
            # 配置获取连接等待超时的时间
            maxWait: 60000
            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            timeBetweenEvictionRunsMillis: 60000
            # 配置一个连接在池中最小生存的时间，单位是毫秒
            minEvictableIdleTimeMillis: 300000
            # 配置一个连接在池中最大生存的时间，单位是毫秒
            maxEvictableIdleTimeMillis: 900000
            # 配置检测连接是否有效
            validationQuery: SELECT 1 FROM DUAL
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            webStatFilter: 
                enabled: true
            statViewServlet:
                enabled: true
                # 设置白名单，不填则允许所有访问
                allow:
                url-pattern: /druid/*
                # 控制台管理用户名和密码
                login-username: 
                login-password: 
            filter:
                stat:
                    enabled: true
                    # 慢SQL记录
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true

# canal配置
canal:
    host: 127.0.0.1
    port: 11111
    destination: example
    username:
    password:

# elasticsearch配置
elasticsearch:
    username:
    password:
    cluster:
        name: elasticsearch
    host: 127.0.0.1
    port: 9300
    index: oms